services:
  soundsright-miner:
    restart: unless-stopped
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - soundsright-subnet:/root/.soundsright-subnet
      - ${HOME}/.bittensor:/root/.bittensor
    build:
      context: .
      dockerfile: miner.Dockerfile
    command: /bin/bash -c "source /soundsright-subnet/.venv/bin/activate && python3 /soundsright-subnet/soundsright/neurons/miner.py --netuid ${NETUID} --subtensor.chain_endpoint ${SUBTENSOR_CHAIN_ENDPOINT} --wallet.name ${WALLET} --wallet.hotkey ${HOTKEY} --log_level ${LOG_LEVEL} --healthcheck_host ${HEALTHCHECK_API_HOST} --healthcheck_port ${HEALTHCHECK_API_PORT}"
  soundsright-miner-dev:
    restart: unless-stopped
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - soundsright-subnet:/root/.soundsright-subnet
      - ${HOME}/.bittensor:/root/.bittensor
    build:
      context: .
      dockerfile: miner.Dockerfile
    command: /bin/bash -c "source /soundsright-subnet/.venv/bin/activate && python3 /soundsright-subnet/soundsright/neurons/miner.py --netuid ${NETUID} --subtensor.chain_endpoint ${SUBTENSOR_CHAIN_ENDPOINT} --wallet.name ${WALLET} --wallet.hotkey ${HOTKEY} --log_level ${LOG_LEVEL} --healthcheck_host ${HEALTHCHECK_API_HOST} --healthcheck_port ${HEALTHCHECK_API_PORT} --validator_min_stake 0"

volumes:
  soundsright-subnet: